export { ChangePasswordPage } from '@/features/auth/pages/ChangePasswordPage'
export { SettingsPage } from '@/features/settings/pages/SettingsPage'
export { UsersListPage as UsersPage } from '@/features/users/pages/UsersListPage'
export { UserCreatePage } from '@/features/users/pages/UserCreatePage'
export { UserDetailPage } from '@/features/users/pages/UserDetailPage'
export { ClassesListPage as ClassesPage } from '@/features/classes/pages/ClassesListPage'
export { ClassDetailPage } from '@/features/classes/pages/ClassDetailPage'
export { QuestionsListPage as QuestionsPage } from '@/features/questions/pages/QuestionsListPage'
export { QuestionFormPage } from '@/features/questions/pages/QuestionFormPage'
export { AssignmentsListPage as AssignmentsPage } from '@/features/assignments/pages/AssignmentsListPage'
export { AssignmentEditPage } from '@/features/assignments/pages/AssignmentEditPage'
export { AssignmentCreatePage } from '@/features/assignments/pages/AssignmentCreatePage'
export { AssignmentDetailPage } from '@/features/assignments/pages/AssignmentDetailPage'
export { TakeAssignmentPage } from '@/features/assignments/pages/TakeAssignmentPage'
export { AssignmentResultPage, AssignmentReviewPage } from '@/features/assignments/pages/AssignmentResultPage'
export { CircularsListPage as CircularsPage } from '@/features/circulars/pages/CircularsListPage'
export { CircularFormPage } from '@/features/circulars/pages/CircularFormPage'
export { CircularDetailPage } from '@/features/circulars/pages/CircularDetailPage'
export { PollsListPage as PollsPage } from '@/features/polls/pages/PollsListPage'
export { PollFormPage } from '@/features/polls/pages/PollFormPage'
export { PollDetailPage } from '@/features/polls/pages/PollDetailPage'
export { AnalyticsPage } from '@/features/analytics/pages/AnalyticsPages'
export { RoleDashboardPage } from '@/features/dashboard/pages/RoleDashboardPage'
